### ISSUE TITLE
Request to add size and position adjustment options

### ISSUE THREAD

**Issue by TFGH164** [Poli93/ArenaNumbers#1]
hi， I am running well on Warname. Can we add adjustment options for position and size?

**Comment by Poli93** [comment]
Hey, Thanks! I've added slash commands to adjust the size and positions, hf ;)

> Usage: /an scale / size <number> - set font size
> Usage: /an x / xpos <number> - set x position
> Usage: /an y / ypos <number> - set y position
> Usage: /an reset - reset settings to default
